# Create enviroment for testing export-sis-alma.
version: "3.7"
services: 
    export-sftp:
        container_name: export-sftp
        build: .
        volumes:
            - ./sshd_config:/etc/ssh/sshd_config:ro
            - ./private/ssh:/etc/ssh/keys:ro
            - ./local/home:/home/sftp:rw
        ports:
            - "2222:22"
        # restart: always

